namespace DotnetCronner;

/// <summary>
/// One recorded execution (a single run) of a <see cref="CronnerJob"/>. This is the unit of
/// execution-history data that flows through an <see cref="ICronnerStore"/>: a run inserts a
/// <see cref="JobExecutionStatus.Running"/> record when it starts and updates that same record to a
/// terminal status when it finishes, correlated by <see cref="Id"/>.
/// </summary>
public sealed class CronnerJobExecution
{
    /// <summary>
    /// A stable per-run correlation id, generated by the scheduler when the run starts. The store uses it to
    /// find and finalize the very row it inserted at start — necessary because a task in
    /// <see cref="CronnerConcurrencyMode.Concurrent"/> mode can have several runs in flight at once, all
    /// sharing the same <see cref="JobId"/>.
    /// </summary>
    public required string Id { get; set; }

    /// <summary>The <see cref="CronnerJob.Id"/> this run belongs to (a recurring task id, or a one-off instance id).</summary>
    public required string JobId { get; set; }

    /// <summary>When the run started (UTC).</summary>
    public DateTimeOffset StartedAt { get; set; }

    /// <summary>When the run finished (UTC), or <c>null</c> while it is still running.</summary>
    public DateTimeOffset? FinishedAt { get; set; }

    /// <summary>
    /// How long the run took — <see cref="FinishedAt"/> minus <see cref="StartedAt"/> — or <c>null</c> while
    /// it is still running. Computed, so it never disagrees with the timestamps and needs no storage.
    /// </summary>
    public TimeSpan? Duration => FinishedAt is { } finished ? finished - StartedAt : null;

    /// <summary>The run's status. <see cref="JobExecutionStatus.Running"/> until it finalizes.</summary>
    public JobExecutionStatus Status { get; set; } = JobExecutionStatus.Running;

    /// <summary>The 1-based attempt number for this run (increments with each automatic retry).</summary>
    public int Attempt { get; set; }

    /// <summary>The error message if the run failed, otherwise <c>null</c>.</summary>
    public string? Error { get; set; }

    /// <summary>
    /// Identifier of the scheduler instance (worker) that ran this execution — answers "which node ran
    /// this". <c>null</c> if not recorded.
    /// </summary>
    public string? Owner { get; set; }

    /// <summary>
    /// Optional consumer data attached to this run, as JSON. <c>null</c> if none.
    /// </summary>
    /// <remarks>
    /// Deprecated: execution history records <em>an execution</em>, not application data. Keep
    /// application-specific data and logs in your own store, correlated by <see cref="Id"/> (the execution id,
    /// exposed at run time as <c>ctx.ExecutionId</c>). This slot is retained for now and will be removed in a
    /// future release.
    /// </remarks>
    [Obsolete("Execution history records an execution, not application data — keep app data/logs in your own store, correlated by the execution id (ctx.ExecutionId). Removed in a future release.")]
    public string? Data { get; set; }

    /// <summary>Creates a shallow copy so stores can hand out snapshots without exposing their internal state.</summary>
    public CronnerJobExecution Clone() => (CronnerJobExecution)MemberwiseClone();
}
